<a href="https://colab.research.google.com/github/mitali-datascientist/Deep-Learning-with-Keras/blob/master/ImageClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Here, using the MNIST dataset available, we'll be builiding an Image Classifier using Neural Networks. 

#### The MNIST database of handwritten digits, available from this page, has a training set of 60,000 examples, and a test set of 10,000 examples. It is a subset of a larger set available from NIST. The digits have been size-normalized and centered in a fixed-size image.
##### It is a good database for people who want to try learning techniques and pattern recognition methods on real-world data while spending minimal efforts on preprocessing and formatting.

In [2]:
#Importing Tensorflow
import tensorflow as tf

In [3]:
#Load dataset 
mnist_data = tf.keras.datasets.mnist

In [4]:
## Convert the samples from integers to floating-point numbers
(x_train, y_train), (x_test, y_test) = mnist_data.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [5]:
## Build the tf.keras.Sequential model by stacking layers. We chose an optimizer and loss function for training
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.27363384, -0.3680734 ,  0.31769925,  0.7294545 ,  0.25029123,
         0.25189787,  0.21874118,  0.1741325 ,  0.02127616,  0.60150874]],
      dtype=float32)

In [7]:
## The tf.nn.softmax function converts these logits to "probabilities" for each class
tf.nn.softmax(predictions).numpy()


array([[0.0596438 , 0.05426886, 0.10774025, 0.16263014, 0.10071706,
        0.10087901, 0.09758904, 0.09333139, 0.08010195, 0.14309844]],
      dtype=float32)

In [8]:
## The losses.SparseCategoricalCrossentropy loss takes a vector of logits and a True index and returns a scalar loss for each example
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [9]:
loss_fn(y_train[:1], predictions).numpy()


2.2938333

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
## The Model.fit method adjusts the model parameters to minimize the loss
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2978 - accuracy: 0.9123
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1445 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1085 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0874 - accuracy: 0.9724
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0747 - accuracy: 0.9758


In [12]:
## The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - loss: 0.0793 - accuracy: 0.9743


[0.0792577937245369, 0.9743000268936157]

In [13]:
## If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1439296e-08, 5.4035922e-09, 1.3926635e-06, 6.1988430e-05,
        1.3749282e-10, 7.8230379e-08, 1.6697964e-13, 9.9992132e-01,
        3.0040049e-08, 1.5065717e-05],
       [3.3183255e-07, 2.3600855e-03, 9.9721056e-01, 4.2234556e-04,
        1.5970061e-16, 5.8359606e-06, 6.3539670e-07, 6.6785418e-12,
        2.2900760e-07, 4.0992106e-11],
       [1.2259059e-07, 9.9912661e-01, 8.9612295e-05, 5.8735473e-06,
        7.7838140e-06, 3.5994306e-06, 2.7902463e-05, 6.7160407e-04,
        6.6020846e-05, 8.9040850e-07],
       [9.9996197e-01, 4.2644450e-07, 3.0414336e-05, 6.1758158e-07,
        3.1118550e-09, 6.8319707e-07, 2.7709145e-06, 1.9413255e-06,
        4.4776061e-11, 1.2069747e-06],
       [5.8661102e-05, 9.6154888e-09, 1.7523973e-05, 3.4852526e-06,
        9.3978381e-01, 3.1251270e-07, 2.3095010e-05, 1.1860802e-04,
        8.3694376e-06, 5.9985962e-02]], dtype=float32)>